# Generated by Django 4.2.28 on 2026-03-17
# Agent-first fields for PlaneAgent

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Add agent-first fields to Issue model.
    
    These fields enable:
    - Agent task claiming (atomic locking)
    - Agent context storage
    - Human review workflow
    - Artifact tracking
    """
    
    dependencies = [
        ('db', '0120_issueview_archived_at'),
    ]
    
    operations = [
        # Agent identification
        migrations.AddField(
            model_name='issue',
            name='assigned_agent',
            field=models.CharField(
                max_length=255, 
                null=True, 
                blank=True,
                help_text='ID of the agent assigned to this task'
            ),
        ),
        
        # Agent context (flexible JSON for agent-specific data)
        migrations.AddField(
            model_name='issue',
            name='agent_context',
            field=models.JSONField(
                default=dict,
                blank=True,
                help_text='Agent-specific context: decisions, discoveries, state'
            ),
        ),
        
        # Can agent execute without approval?
        migrations.AddField(
            model_name='issue',
            name='auto_executable',
            field=models.BooleanField(
                default=False,
                help_text='Agent can start without human approval'
            ),
        ),
        
        # Does this need human review after completion?
        migrations.AddField(
            model_name='issue',
            name='human_review_required',
            field=models.BooleanField(
                default=True,
                help_text='Requires human review after agent completion'
            ),
        ),
        
        # Agent-specific status (separate from issue state)
        migrations.AddField(
            model_name='issue',
            name='agent_status',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('unclaimed', 'Unclaimed'),
                    ('claimed', 'Claimed'),
                    ('in_progress', 'In Progress'),
                    ('blocked', 'Blocked'),
                    ('completed', 'Completed'),
                    ('verified', 'Verified'),
                ],
                default='unclaimed',
                help_text='Agent workflow status'
            ),
        ),
        
        # Why is this blocked?
        migrations.AddField(
            model_name='issue',
            name='blocked_reason',
            field=models.TextField(
                null=True, 
                blank=True,
                help_text='Reason task is blocked'
            ),
        ),
        
        # Artifacts (screenshots, logs, files)
        migrations.AddField(
            model_name='issue',
            name='artifacts',
            field=models.JSONField(
                default=list,
                blank=True,
                help_text='List of artifacts: [{type, url, description, timestamp}]'
            ),
        ),
        
        # When was this claimed by an agent?
        migrations.AddField(
            model_name='issue',
            name='claimed_at',
            field=models.DateTimeField(
                null=True, 
                blank=True,
                help_text='When agent claimed this task'
            ),
        ),
        
        # When was this verified by a human?
        migrations.AddField(
            model_name='issue',
            name='verified_at',
            field=models.DateTimeField(
                null=True, 
                blank=True,
                help_text='When human verified the completed work'
            ),
        ),
        
        # Who verified this?
        migrations.AddField(
            model_name='issue',
            name='verified_by',
            field=models.ForeignKey(
                'db.User',
                on_delete=models.SET_NULL,
                null=True,
                blank=True,
                related_name='verified_issues',
                help_text='User who verified this task'
            ),
        ),
    ]
